<?php

namespace Database\Seeders;

use App\Models\ApplianceType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\DefaultAppliance;
use App\Models\DeviceType;
use Illuminate\Database\Seeder;

class DefaultApplianceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $default_appliances = [

            [
                'model' => 'TIS-DMX-48',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '5',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-4DI-IN',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '4',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'HVAC6-3A-T',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-PIR-CM',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-IR-CUR',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ES-10F-CM',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'RLY-4CH-10A',
                'switch' => '4',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VLC-6CH-3A',
                'switch' => '6',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'RLY-8CH-16A',
                'switch' => '8',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VLC-12CH-10A',
                'switch' => '12',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DIM-6CH-2A',
                'switch' => '0',
                'dimmer' => '6',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DIM-4CH-3A',
                'switch' => '0',
                'dimmer' => '4',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DIM-2CH-6A',
                'switch' => '0',
                'dimmer' => '2',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-AUT-TMR',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IP-COM-PORT-OLD',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-SEC-SM',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '1',
                'motor' => '0',
            ],
            [
                'model' => 'TER-4G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TER-ACT',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TER-AUD',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MRS-4G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MRS-8G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MRS-12G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MRS-AC10G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DALI-64',
                'switch' => '0',
                'dimmer' => '12',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-DIM-4CH-1A',
                'switch' => '0',
                'dimmer' => '4',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DIM-TE-2CH-3A',
                'switch' => '0',
                'dimmer' => '2',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DIM-TE-4CH-1.5A',
                'switch' => '0',
                'dimmer' => '4',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'RCU-8OUT-8IN',
                'switch' => '8',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '8',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'RLY-6CH-0-10V',
                'switch' => '0',
                'dimmer' => '6',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-TFT-43',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-9GANGS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-BEDSIDE',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-BELL-3S',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-M3-MOTOR',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '1',
            ],
            [
                'model' => 'IO-8G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-AC-4G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-6S-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIT-2G-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIT-3G-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIT-4G-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TARIQ-8G6R5Z',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TARIQ-8G3R5Z1F',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TARIQ-8G3R5Z2D',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-HEALTH-CM',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-2S-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-3S-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-4S-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-3R-HC-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-4R-HC-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-5R-LC-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'RCU-24R20Z',
                'switch' => '24',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '20',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIT-TFT-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'RCU-20R20Z-IP',
                'switch' => '20',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '20',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ACM-1D-2Z',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-4T-IN',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DIM-W06CH10A-TE',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'DIM-W12CH10A-TE',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MINI-AIR-AUTO-IRE-T',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'BUS-PIR-CM',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'BUS-ES-IR',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ADS-3R-BUS',
                'switch' => '3',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ACM-3Z-IN',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '3',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'AIR-AUTO-IRE-T',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'BUS-AUTO-IRE-T',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'AIR-ES-IR',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ADS-1D-1Z',
                'switch' => '0',
                'dimmer' => '1',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ADS-2R-2Z',
                'switch' => '2',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '2',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'AIR-PIR-CM',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-4S-4R-HC',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-5R-LC',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-4R-HC',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'AIR-1IRE-T',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'AIR-2IRE',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ACM-2R-2Z',
                'switch' => '2',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '2',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-2S-2R-HC',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-3R-HC',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ADS-4CH-0-10V',
                'switch' => '0',
                'dimmer' => '4',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'ADS-3R-3Z',
                'switch' => '3',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '3',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'AMP-5S1Z-MTX',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'AIR-SOCKET-S',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-1D-UV',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-3S-3R-HC',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-AIR-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'PRJ-LFT-15K-130',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-WS-71',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IP-COM-PORT',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MET-EN-1PH',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-KNX-PORT',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-TRV-16CNV',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-IN-HOTEL-HRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-IN-HOTEL-3T3L-HRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-IN-HOTEL-HRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-OUT-HOTEL-HRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-OUT-HOTEL',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-OUT-HOTEL-HRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-OUT-HOTEL',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-MER-8G-PB',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-MER-AC4G-PB',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-IN-HOTEL-LRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-OUT-HOTEL-LRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-IN-HOTEL-LRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-OUT-HOTEL-LRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-IN-HOTEL-3T3L-LRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-ZIG-PORT',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-AUD-SRV-4X-160W',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-M7-CURTAIN',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '1',
            ],
            [
                'model' => 'VEN-2G-HC-BUS-B',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-3G-HC-BUS-B',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-4G-HC-BUS-B',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-3R-1.5-OLED-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-4R-1.5-OLED-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-5R-1.5-OLED-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-3R-1.5-OLED',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-4R-1.5-OLED',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-AC-5R-1.5-OLED',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-VRV-PRO',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-2G-HC-AIR-A',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-3G-HC-AIR-A',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'VEN-4G-HC-AIR-A',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-BEDSIDE-12G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-BUS-CONVERTER',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-4CH-AIN',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-OUTDOOR-BELL',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-SOL-3G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MER-IN-HOTEL-LRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TER-2G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-SOL-TFT',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MER-OUT-HOTEL-LRF',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-GTY-1AC',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-OUT-HOTEL-HRF-809A',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-OUT-HOTEL-809B',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-OUT-HOTEL-HRF-809C',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'LUNA-OUT-HOTEL-809D',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'IO-IN-HOTEL-HRF-809E',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'CLICK-1G-PANEL-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'CLICK-2G-PANEL-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'CLICK-3G-PANEL-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'CLICK-4G-PANEL-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'CLICK-6G-PANEL-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-SEC-PRO',
                'switch' => '1',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '4',
                'AC' => '0',
                'security' => '1',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-CLICK-AC-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-22DI-DIN',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '22',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MER-IN-HOTEL-HRF-0x80AA',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-4AI-010V',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-4AI-4-20MA',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'MER-OUT-HOTEL-HRF-0x80AD',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-HEALTH-CM-RADAR',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '1',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-ZB-GATEWAY',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-RADAR-SENSOR',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '2',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-ERO-1G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-ERO-2G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-ERO-3G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-ERO-4G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-ERO-6G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-CLICK-AC-FH-BUS',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '1',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-C-BUS-CONVERTER',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-FAN-4CH',
                'switch' => '4',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-SIR-4G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-SIR-6G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-SIR-8G',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '0',
            ],
            [
                'model' => 'TIS-TM-120',
                'switch' => '0',
                'dimmer' => '0',
                'rgbw' => '0',
                'Binary Sensor' => '0',
                'AC' => '0',
                'security' => '0',
                'motor' => '1',
            ]
        ];
        // truncate default_appliances table
        DefaultAppliance::truncate();
        // create default_appliances records
        foreach ($default_appliances as $default_appliance) {
            $model = $default_appliance['model'];
            $switch_appliances = $default_appliance['switch'];
            $dimmer_appliances = $default_appliance['dimmer'];
            $rgbw_appliances = $default_appliance['rgbw'];
            $binary_sensor_appliances = $default_appliance['Binary Sensor'];
            $ac_appliances = $default_appliance['AC'];
            $security_appliances = $default_appliance['security'];
            $cover_with_pos_appliances = $default_appliance['motor'];
            // fetch model id
            $device_type = DeviceType::where('device_type_name', $model)->first();
            // create default_appliances records for each appliance type
            if ($switch_appliances > 0) {
                for ($i = 1; $i <= $switch_appliances; $i++) {
                    $appliance = DefaultAppliance::create(
                        [
                            'device_type' => $device_type->id,
                            'appliance_type' => ApplianceType::where('appliance_type_name', 'switch')->first()->id,
                            'appliance_identifier' => $i,
                        ]
                    );
                };
            };
            if ($dimmer_appliances > 0) {
                for ($i = 1; $i <= $dimmer_appliances; $i++) {
                    $appliance = DefaultAppliance::create(
                        [
                            'device_type' => $device_type->id,
                            'appliance_type' => ApplianceType::where('appliance_type_name', 'dimmer')->first()->id,
                            'appliance_identifier' => $i,
                        ]
                    );
                };
            };
            if ($rgbw_appliances > 0) {
                for ($i = 1; $i <= $rgbw_appliances; $i++) {
                    $appliance = DefaultAppliance::create(
                        [
                            'device_type' => $device_type->id,
                            'appliance_type' => ApplianceType::where('appliance_type_name', 'rgbw')->first()->id,
                            'appliance_identifier' => $i,
                        ]
                    );
                };
            };
            if ($binary_sensor_appliances > 0) {
                for ($i = 1; $i <= $binary_sensor_appliances; $i++) {
                    $appliance = DefaultAppliance::create(
                        [
                            'device_type' => $device_type->id,
                            'appliance_type' => ApplianceType::where('appliance_type_name', 'binary_sensor')->first()->id,
                            'appliance_identifier' => $i,
                        ]
                    );
                };
            };
            if ($ac_appliances > 0) {
                for ($i = 1; $i <= $ac_appliances; $i++) {
                    $appliance = DefaultAppliance::create(
                        [
                            'device_type' => $device_type->id,
                            'appliance_type' => ApplianceType::where('appliance_type_name', 'ac')->first()->id,
                            'appliance_identifier' => $i,
                        ]
                    );
                };
            };
            if ($security_appliances > 0) {
                for ($i = 1; $i <= $security_appliances; $i++) {
                    $appliance = DefaultAppliance::create(
                        [
                            'device_type' => $device_type->id,
                            'appliance_type' => ApplianceType::where('appliance_type_name', 'security')->first()->id,
                            'appliance_identifier' => $i,
                        ]
                    );
                };
            };
            if ($cover_with_pos_appliances > 0) {
                for ($i = 1; $i <= $cover_with_pos_appliances; $i++) {
                    $appliance = DefaultAppliance::create(
                        [
                            'device_type' => $device_type->id,
                            'appliance_type' => ApplianceType::where('appliance_type_name', 'motor')->first()->id,
                            'appliance_identifier' => $i,
                        ]
                    );
                };
            };
        }
    }
}
